---
#
# l3d.users
# l3d.users.user
# -> define users
l3d_users__default_users:
 - name: 'l3d'
   state: 'present'
   shell: '/bin/bash'
   create_home: true
   pubkeys: "{{ lookup('url', 'https://github.com/do1jlr.keys', split_lines=False) }}"
   exklusive_pubkeys: true
   admin: true
   admin_commands: 'ALL'
   admin_nopassword: false
   admin_ansible_login: true
 - name: 'alice'
   state: 'absent'

#
# l3d.users
# l3d.users.user
# -> enable keychain as ssh agent
l3d_users__dotfiles__additional_user_bashrc_lines:
 - '[[ $- == *i* ]] && eval $(keychain --eval --quiet id_ed25519)'
 - '_gopass_bash_autocomplete() {'
 - '   local cur opts base'
 - '   COMPREPLY=()'
 - '   cur="${COMP_WORDS[COMP_CWORD]}"'
 - '   opts=$( ${COMP_WORDS[@]:0:$COMP_CWORD} --generate-bash-completion )'
 - "   local IFS=$'\n'"
 - '   COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )'
 - '   return 0'
 - '}'
 - 'complete -F _gopass_bash_autocomplete gopass'


# roles/authorized_keys
#
# define dir for ssh keys
ssh_public_key_store: 'admin_ssh_keys'

i3_keybindings_extra:
 - keybinding:
   name: Volume (mute/unmute)
   key: $mod+F12
   exec: --no-startup-id pulsemixer --toggle-mute
 - keybinding:
   name: Volue (default)
   key: $mod+Shift+F12
   exec: --no-startup-id pulsemixer --set-volume 42
 - keybinding:
   name: volume-up
   key: XF86AudioRaiseVolume
   exec: --no-startup-id pulsemixer --change-volume +3
 - keybinding:
   name: volume-down
   key: XF86AudioLowerVolume
   exec: --no-startup-id pulsemixer --change-volume -5
 - keybinding:
   name: darker
   key: XF86AudioMute
   exec: --no-startup-id pulsemixer --toggle-mute
 - keybinding:
   name: darker
   key: XF86MonBrightnessDown
   exec: --no-startup-id sudo light -U 9
 - keybinding:
   name: lighter
   key: XF86MonBrightnessUp
   exec: --no-startup-id sudo light -A 6

i3_applications:
 - application:
   class: "firefox"
   name: "firefox"
   workspace: 2
   on_startup: true
 - application:
   class: "Thunderbird"
   name: "thunderbird"
   workspace: 9
   on_startup: true

i3_run_on_startup:
 # - nextcloud
 - sudo nm-applet

# roles/do1jlr.base
l3d_pkgs__install_advanced: true
l3d_pkgs__install_python: true
l3d_pkgs__install_cli: true
l3d_pkgs__install_extra_packages:
 - keychain

# globaly enably simple versionscheck - if available
submodules_versioncheck: true
