---
#
# l3d.users
# l3d.users.user
l3d_users__local_users:
  - name: 'lilian'
    state: 'present'
    shell: '/bin/bash'
    create_home: true
    pubkeys: "{{ lookup('url', 'https://github.com/do1jlr.keys', split_lines=False) }}"
    password: "{{ lookup('community.general.passwordstore', 'private/ansible/hosts/' + inventory_hostname + '/users/lilian/pwd_hash') }}"
    exklusive_pubkeys: true
    admin: true
    admin_commands: 'ALL'
    admin_nopassword: false
    admin_ansible_login: true
    groups: ['libvirt']
l3d_users__additional_groups: ['libvirt']

# l3d.packages
packages__install_extra_packages:
  - virt-manager

# gopass dir
gopass_prefix: 'private/'

# Collection l3d.wm
## l3d.wm.sway
sway__user_list:
  - user: "l3d"
    home: "/home/l3d"
  - user: 'lilian'
    home: '/home/lilian'

# Collection l3d.users
## l3d.users.dotfiles
l3d_users__dotfiles__variables:
  - {var: "EDITOR", command: "/usr/bin/vim"}
  - {var: "VISUAL", command: "/usr/bin/vim"}
