---

- name: Install useful packages
  hosts: thinkpad
  tags: 
  - packages
  - updates
  - setup
  roles:
    - workstation_packages

- name: enable and secure sshd
  hosts: thinkpad
  tags: 
  - secure
  - ssh
  - setup
  roles:
    - authorized_keys
    - sshd

- name: Install useful dotfiles
  hosts: thinkpad
  tags: 
  - setup
  roles:
    - dotfiles

- name: install modules for sound and bluetooth
  hosts: thinkpad
  tags:
  - setup
  - pulseaudio
  - networkmanager
  roles:
    - pulseaudio
    - networkmanager

#- name: improve firefox configuration
#  hosts: thinkpad
#  tags:
#  - setup
#  - firefox
#  roles:
#    - firefox


- name: Install useful packages
  hosts: thinkpad
  tags: 
  - packages
  - i3wm
  roles:
    - copy_files
    - i3wm

- name: install nextcloud-client
  hosts: thinkpad
  tags:
  - setup
  - nextcloud
  roles:
    - nextcloud



