---
- name: check if ansible is not to old
  hosts: localhost
  roles:
    - {role: ansible_version, tags: always, gather_facts: false}

- name: base packages setup
  hosts: l14.local
  roles:
    - {role: workstation_packages, tags: [base, packages, workstation]}
    - {role: amdgpu_firmware, tags: [amdgpu, firmware]}

- name: user and ssh(d) setup
  hosts: l14.local
  roles:
    - {role: do1jlr.users, tags: [users, base]}
    - {role: do1jlr.auth, tags: [auth, base]}
    - {role: do1jlr.sshd, tags: [sshd, base]}
    - {role: dotfiles, tags: [dotfiles, base]}

- name: fancy schnickschnack
  hosts: l14.local
  roles:
    - {role: akku-warning, tags: akku}
    - {role: pulseaudio, tags: [pulse, audio, pulseaudio]}
    - {role: networkmanager, tags: networkmanager, when: ansible_os_family == 'Archlinux'}
    - {role: openvpn, tags: ovpn}
    - {role: nextcloud, tags: nextcloud, when: ansible_os_family == 'Archlinux'}
    - {role: bat, tags: bat, when: ansible_os_family == 'Debian'}
    - {role: install-firefox, tags: firefox}
    - {role: copy_files}
    - {role: i3wm, tags: i3wm}
    - {role: ntp, tags: ntp}
    - {role: xrandr, tags: xrandr}
    - {role: arch-fonts, tags: fonts}
    - {role: winehq, tags: wine}
    - {role: no-sleep, tags: sleep}
    - {role: do1jlr.avahi_daemon, tags: [avahi_daemon, avahi]}
    - {role: do1jlr.avahi_client, tags: [avahi_client, mdns]}
