---
- name: Check if ansible is not to old
  hosts: all
  roles:
    - {role: ansible_version, tags: always}

- name: Generic Workstation Preperation
  hosts: all
  roles:
    - {role: l3d.packages, tags: [packages, apt]}
    - {role: l3d.ntp, tags: ntp}
    - {role: l3d.avahi.client, tags: avahi}
    - {role: l3d.avahi.daemon, tags: avahi}
    - {role: l3d.etesync_dav, tags: [etebase, etesync, dav]}
    - {role: gantsign.bat, tags: bat}
    - {role: l3d.gopass, tags: gopass}
    - {role: do1jlr.i3wm, tags: i3wm}

# - name: user specific setup
#   hosts: private
#   roles:
#     - {role: dotfiles, tags: [default, dotfiles, fancy]}
#     - {role: manage_users, tags: [ssh, manage, manage_users]}
#     - {role: authorized_keys, tags: [ssh, auth, authorized_keys]}
#     - {role: sshd, tags: [ssh, sshd]}
#     - {role: akku-warning, tags: [akku, akku_warning, akku-warning]}
#     - {role: pulseaudio, tags: pulseaudio}
#     - {role: networkmanager, tags: [nm, networkmanager]}
#     - {role: openvpn, tags: openvpn}
#     - {role: winehq, tags: [wine, winehq]}
#     - {role: no-sleep, tags: no_sleep}
