---
- name: Check if ansible is not to old
  hosts: all
  roles:
    - {role: ansible_version, tags: always}

- name: Setup GoPass
  hosts: all
  roles:
    - {role: roles-ansible.gopass, tags: gopass}

- name: Generic Workstation Preperation
  hosts: [work, private]
  roles:
    - {role: l3d.users.user, tags: user}
    - {role: l3d.users.admin, tags: admin}
    - {role: l3d.users.sshd, tags: sshd}
    - {role: l3d.users.dotfiles, tags: dotfiles}

- name: Generic Workstation Preperation
  hosts: [work, private]
  roles:
    - {role: l3d.packages, tags: [packages, apt]}
    - {role: l3d.time.ntp, tags: ntp}
    - {role: l3d.avahi.client, tags: avahi}
    - {role: l3d.avahi.daemon, tags: avahi}
    - {role: l3d.etesync_dav, tags: [etebase, etesync, dav]}
    - {role: gantsign.bat, tags: bat}
    - {role: l3d.wm.i3, tags: i3wm}
    - {role: l3d.wm.sway, tags: sway}
    - {role: l3d.linux.librewolf, tags: librewolf}
    # - {role: amdgpu_firmware, tags: firmware}
    - {role: do1jlr.htop, tags: htop}

# - name: user specific setup
#   hosts: private
#   roles:
#     - {role: akku-warning, tags: [akku, akku_warning, akku-warning]}
#     - {role: no-sleep, tags: no_sleep}

- name: Setup business specific stuff
  hosts: work
  roles:
    - {role: openvpn, tags: openvpn}
