---
# local user config:
users:
  lilian:
    - l3d@derpy.l3d.yt
    - l3d@mobile.l3d.yt
    - l3d@pinkie.l3d.yt
    - l3d@business.wingcon.com
    - l3d@backup.l3d.yt
    - l3d@backup-rsa.l3d.yt

admins:
  - lilian

base__additional_user_bashrc_lines:
  - '[[ $- == *i* ]] && eval $(keychain --eval --quiet id_ed25519)'

# used to automatically generate correct admin keys
admins_ssh_root_prefix:
  - l3d

accounts:
  - lilian

akku_user: "lilian"
wine_user: "lilian"
wine_user_home: "/home/lilian"
copy_to_user: "{{ akku_user }}"
