---
# local user config:
users:
  l3d:
    - l3d@backup.l3d.yt
    - l3d@derpy.l3d.yt
    - l3d@mobile.l3d.yt
    - l3d@pinkie.l3d.yt
    - l3d@business.wingcon.com

admins:
  - l3d

accounts:
  - l3d

akku_user: "l3d"
