---
- include_tasks: versioncheck.yml
  when: submodules_versioncheck|bool

- name: install needed packages on arch
  become: yes
  community.general.pacman:
    name:
     - wireless_tools
     - iw 
     - crda
     - networkmanager
     - dnsutils
     - mtr
    state: latest
  when: ansible_distribution == 'Archlinux'

- name: install Networkmanager
  become: yes
  ansible.builtin.dnf:
    name: NetworkManager
    state: present
  when: ansible_distribution == 'Fedora'

- name: install NetworkManager
  become: yes
  ansible.builtin.apt:
    name: networkmanager
    state: present
  when: ansible_os_family == 'Debian'

- name: install needed packages for NetworkManager
  become: yes
  ansible.builtin.package:
    name:
     - dialog
     - wpa_supplicant
     - network-manager-applet
     - nm-connection-editor
    state: present

- name: enable networkmanager
  become: yes
  ansible.builtin.systemd:
    name: NetworkManager.service
    enabled: yes
