---
name: Ansible Lint check

# yamllint disable-line rule:truthy
on: [push, pull_request]

jobs:
  build:
    name: Ansible Lint
    runs-on: ubuntu-latest

    steps:
      - name: 'checkout git repo'
        uses: actions/checkout@v4.1.1
        with:
          lfs: true
          submodules: true
          fetch-depth: 0

      - name: Run ansible-lint
        uses: ansible-actions/ansible-lint-action@v1.0.2
        with:
          target: "site.yml"
