---
name: 'Yamllint GitHub Actions'

# yamllint disable-line rule:truthy
on: [push, pull_request]

jobs:
  yamllint:
    name: 'Yamllint'
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout git repo'
        uses: actions/checkout@v4.1.1

      - name: 'Yamllint'
        uses: karancode/yamllint-github-action@v2.1.1
        with:
          yamllint_file_or_dir: '.'
          yamllint_config_filepath: './.yamllint'
