---
- name: Perform versionscheck
  ansible.builtin.include_tasks:
    file: 'versioncheck.yml'

- name: Install openvpn packages
  ansible.builtin.include_tasks:
    file: 'install.yml'

- name: Make sure openvpn modules are present
  ansible.builtin.include_tasks:
    file: 'modprobe.yml'
